export type StrainType = 'Indica' | 'Sativa' | 'Hybrid';
export type Difficulty = 'Easy' | 'Moderate' | 'Hard';
export type StrainEra = 'Landrace' | 'Legacy' | 'Modern';

export interface StrainInfo {
  id: string;
  name: string;
  type: StrainType;
  era: StrainEra;
  thcContent: string;
  cbdContent?: string;
  difficulty: Difficulty;
  growthTime: string;
  expectedYield: string;
  growingTips: string[];
  medicalUses: string[];
  effects: string[];
  imageUrl: string;
  description: string;
  lineage: {
    parents: string[];
    origin?: string;
    heritage?: string;
  };
  breeder?: string;
  funFact?: string;
}

const strainDatabase: StrainInfo[] = [

  // ─── LANDRACES ────────────────────────────────────────────────────────────

  {
    id: 'lambs_bread',
    name: "Lamb's Bread",
    type: 'Sativa',
    era: 'Landrace',
    thcContent: '16% - 21%',
    cbdContent: '0.3%',
    difficulty: 'Moderate',
    growthTime: '10-12 weeks',
    expectedYield: 'Medium (350g/m²)',
    growingTips: [
      'Thrives in warm, humid tropical climates — mimick Jamaica\'s environment indoors.',
      'Stretches dramatically in flower; use SCROG or topping early.',
      'Prefers organic soil over hydroponics to express its full terpene profile.',
    ],
    medicalUses: ['Depression', 'Fatigue', 'Stress', 'Lack of Motivation'],
    effects: ['Euphoric', 'Energetic', 'Uplifted', 'Creative', 'Focused'],
    imageUrl: 'https://images.unsplash.com/photo-1603909223427-51f4f9c6c43e?auto=format&fit=crop&q=80&w=400',
    description: "Jamaica's most sacred strain and Bob Marley's legendary daily smoke. Lamb's Bread — also spelled Lamb's Breath — is a bright green, sticky sativa that delivers a sharp, energetic cerebral high. It has been a cornerstone of Rastafarian spiritual practice for generations.",
    lineage: { parents: ['Jamaican Landrace'], origin: 'Jamaica', heritage: 'Pure Jamaican Sativa' },
    funFact: "Bob Marley called Lamb's Bread 'the herb of life' and credited it with much of his creative inspiration.",
  },
  {
    id: 'afghani',
    name: 'Afghani',
    type: 'Indica',
    era: 'Landrace',
    thcContent: '17% - 20%',
    cbdContent: '0.6%',
    difficulty: 'Easy',
    growthTime: '7-8 weeks',
    expectedYield: 'High (500g/m²)',
    growingTips: [
      'Extremely hardy — tolerates cooler temps and temp swings well.',
      'Produces enormous amounts of resin; ideal for hash production.',
      'Finishes very early; great for multiple harvests per year.',
    ],
    medicalUses: ['Insomnia', 'Chronic Pain', 'Muscle Spasms', 'Anxiety', 'PTSD'],
    effects: ['Deeply Relaxed', 'Sedated', 'Euphoric', 'Sleepy', 'Peaceful'],
    imageUrl: 'https://images.unsplash.com/photo-1542385108-7a544d6db8b1?auto=format&fit=crop&q=80&w=400',
    description: 'The mother of all indicas. Originating from the harsh mountain valleys of Afghanistan and Pakistan, this ancient landrace is the genetic foundation of nearly every modern indica variety in existence. Dense, frosty buds with an earthy, hash-like aroma.',
    lineage: { parents: ['Afghan Landrace'], origin: 'Afghanistan / Pakistan', heritage: 'Pure Hindu Kush Indica' },
    funFact: 'Afghani has been cultivated for over 3,000 years and was brought to the West along the Hippie Trail in the 1960s-70s.',
  },
  {
    id: 'hindu_kush',
    name: 'Hindu Kush',
    type: 'Indica',
    era: 'Landrace',
    thcContent: '15% - 20%',
    cbdContent: '1%',
    difficulty: 'Easy',
    growthTime: '7-8 weeks',
    expectedYield: 'Medium (400g/m²)',
    growingTips: [
      'Naturally compact — perfect for small grow spaces.',
      'Remarkably mold and pest resistant due to its thick resin coat.',
      'Thrives in cool, dry environments similar to its native mountain range.',
    ],
    medicalUses: ['Pain Relief', 'Insomnia', 'Nausea', 'Stress', 'Appetite Loss'],
    effects: ['Relaxed', 'Sleepy', 'Happy', 'Hungry', 'Calm'],
    imageUrl: 'https://images.unsplash.com/photo-1596726581451-b8449c289ad6?auto=format&fit=crop&q=80&w=400',
    description: 'Named after the 800km Hindu Kush mountain range stretching between Afghanistan and Pakistan, this pure indica landrace developed a thick protective coat of trichomes to survive the harsh alpine climate. One of the most historically significant strains ever cultivated.',
    lineage: { parents: ['Hindu Kush Landrace'], origin: 'Afghanistan / Pakistan', heritage: 'Pure Mountain Indica' },
    funFact: 'Hindu Kush is the direct ancestor of the entire Kush family, including OG Kush, Bubba Kush, and Master Kush.',
  },
  {
    id: 'durban_poison',
    name: 'Durban Poison',
    type: 'Sativa',
    era: 'Landrace',
    thcContent: '17% - 26%',
    cbdContent: '0.1%',
    difficulty: 'Easy',
    growthTime: '8-9 weeks',
    expectedYield: 'Medium (450g/m²)',
    growingTips: [
      'One of the fastest-finishing pure sativas — unusually short flower time for its type.',
      'Produces exceptionally large, round resin glands; ideal for extractions.',
      'Very tolerant of cold and humidity variations.',
    ],
    medicalUses: ['Depression', 'Anxiety', 'Fatigue', 'ADHD', 'Nausea'],
    effects: ['Energetic', 'Uplifted', 'Happy', 'Focused', 'Creative'],
    imageUrl: 'https://images.unsplash.com/photo-1603909223427-51f4f9c6c43e?auto=format&fit=crop&q=80&w=400',
    description: "South Africa's gift to the cannabis world. Durban Poison is a beloved pure sativa from the port city of Durban, known for its sweet anise-like aroma, enormous trichome production, and clean, clear-headed euphoria. A parent of Girl Scout Cookies.",
    lineage: { parents: ['South African Landrace'], origin: 'Durban, South Africa', heritage: 'Pure African Sativa' },
    funFact: 'Durban Poison was brought to the US in the 1970s by cannabis pioneer Ed Rosenthal, who collected seeds directly from South Africa.',
  },
  {
    id: 'acapulco_gold',
    name: 'Acapulco Gold',
    type: 'Sativa',
    era: 'Landrace',
    thcContent: '15% - 23%',
    cbdContent: '0.1%',
    difficulty: 'Hard',
    growthTime: '10-11 weeks',
    expectedYield: 'Medium (350g/m²)',
    growingTips: [
      'Requires long warm seasons — best grown outdoors in tropical or subtropical climates.',
      'Produces golden-amber trichomes that give it its iconic coloring.',
      'One of the most difficult landraces to grow at scale; rewards patient cultivators.',
    ],
    medicalUses: ['Fatigue', 'Stress', 'Nausea', 'Pain', 'Depression'],
    effects: ['Euphoric', 'Energizing', 'Uplifted', 'Happy', 'Creative'],
    imageUrl: 'https://images.unsplash.com/photo-1629851722960-9ea3c7885b0d?auto=format&fit=crop&q=80&w=400',
    description: 'One of the most legendary strains of the 1960s and 70s, Acapulco Gold hails from the coastal city of Acapulco, Mexico. Its burnt orange and gold-flecked buds with a caramel-toffee scent made it the premier cannabis of the counterculture era.',
    lineage: { parents: ['Mexican Landrace'], origin: 'Acapulco, Mexico', heritage: 'Pure Mexican Sativa' },
    funFact: 'Acapulco Gold was so revered in the 70s that it was featured in Time Magazine and became a symbol of premium cannabis.',
  },
  {
    id: 'colombian_gold',
    name: 'Colombian Gold',
    type: 'Sativa',
    era: 'Landrace',
    thcContent: '14% - 19%',
    cbdContent: '0.2%',
    difficulty: 'Moderate',
    growthTime: '11-12 weeks',
    expectedYield: 'Medium (300g/m²)',
    growingTips: [
      'Needs a long, warm, humid growing season — ideal for outdoor equatorial climates.',
      'A parent strain of Skunk #1 and many other classic hybrids.',
      'Provides a clear, spacious high without anxiety — even suitable for beginners consuming.',
    ],
    medicalUses: ['Depression', 'Fatigue', 'Stress', 'Mood Disorders'],
    effects: ['Energetic', 'Uplifted', 'Creative', 'Social', 'Clear-headed'],
    imageUrl: 'https://images.unsplash.com/photo-1603909223427-51f4f9c6c43e?auto=format&fit=crop&q=80&w=400',
    description: 'A pure sativa landrace from the Santa Marta mountains of Colombia. Colombian Gold was the most sought-after cannabis in America throughout the 1970s — famously smuggled north and traded for gold. Its lineage flows through nearly every modern hybrid.',
    lineage: { parents: ['Colombian Landrace'], origin: 'Santa Marta, Colombia', heritage: 'Pure Colombian Sativa' },
    funFact: 'Colombian Gold is a grandparent of Skunk #1, which itself became a parent of hundreds of modern strains.',
  },
  {
    id: 'panama_red',
    name: 'Panama Red',
    type: 'Sativa',
    era: 'Landrace',
    thcContent: '10% - 16%',
    cbdContent: '0.3%',
    difficulty: 'Hard',
    growthTime: '11-12 weeks',
    expectedYield: 'Low (250g/m²)',
    growingTips: [
      'Best cultivated outdoors in tropical climates with a long warm season.',
      'Very slow grower — patience is essential.',
      'Old-school genetics that produce a uniquely clear, functional high despite lower THC.',
    ],
    medicalUses: ['Depression', 'Fatigue', 'Stress', 'Creative Blocks'],
    effects: ['Happy', 'Euphoric', 'Energetic', 'Giggly', 'Talkative'],
    imageUrl: 'https://images.unsplash.com/photo-1603909223427-51f4f9c6c43e?auto=format&fit=crop&q=80&w=400',
    description: 'A counterculture icon of the late 1960s and early 70s, Panama Red was the strain of Woodstock and the Summer of Love. Its long, wispy red-haired buds delivered a slow-building, euphoric high that became the standard by which all sativas were measured.',
    lineage: { parents: ['Panamanian Landrace'], origin: 'Panama', heritage: 'Pure Central American Sativa' },
    funFact: 'Panama Red inspired music, poetry, and an entire generation — it was even name-dropped in a New Riders of the Purple Sage song.',
  },
  {
    id: 'thai',
    name: 'Thai (Thai Stick)',
    type: 'Sativa',
    era: 'Landrace',
    thcContent: '12% - 22%',
    cbdContent: '0.1%',
    difficulty: 'Hard',
    growthTime: '12-14 weeks',
    expectedYield: 'Medium (300g/m²)',
    growingTips: [
      'Requires very long growing season — outdoor in tropical/subtropical regions only.',
      'One of the genetic parents of Voodoo, Juicy Fruit, and many 90s strains.',
      'Extremely difficult to grow outside its native climate.',
    ],
    medicalUses: ['Depression', 'Fatigue', 'Creative Blocks', 'Stress'],
    effects: ['Cerebral', 'Energetic', 'Psychedelic', 'Euphoric', 'Focused'],
    imageUrl: 'https://images.unsplash.com/photo-1603909223427-51f4f9c6c43e?auto=format&fit=crop&q=80&w=400',
    description: 'Thai Stick refers to the traditional way cannabis was prepared in Thailand — buds tied around bamboo sticks and coated in hash oil. The genetics from these legendary Thai sativas form the backbone of the famous Haze family and countless other classics.',
    lineage: { parents: ['Thai Landrace'], origin: 'Thailand', heritage: 'Pure Southeast Asian Sativa' },
    funFact: 'Thai genetics were crossbred with Colombian and Mexican landraces by American breeders in the 1970s to create the legendary "Haze" strain.',
  },

  // ─── LEGACY ───────────────────────────────────────────────────────────────

  {
    id: 'jack_herer',
    name: 'Jack Herer',
    type: 'Sativa',
    era: 'Legacy',
    thcContent: '18% - 24%',
    cbdContent: '0.1%',
    difficulty: 'Moderate',
    growthTime: '10-11 weeks',
    expectedYield: 'Medium (450g/m²)',
    growingTips: [
      'Performs best indoors or in warm, Mediterranean-like climates.',
      'Produces four distinct phenotypes — some indica-leaning, some very sativa.',
      'Responds excellently to topping and LST training.',
    ],
    medicalUses: ['Depression', 'Fatigue', 'Anxiety', 'PTSD', 'Stress'],
    effects: ['Creative', 'Energetic', 'Happy', 'Focused', 'Inspired'],
    imageUrl: 'https://images.unsplash.com/photo-1629851722960-9ea3c7885b0d?auto=format&fit=crop&q=80&w=400',
    description: "Named after the cannabis legalization activist and author of 'The Emperor Wears No Clothes,' Jack Herer is a masterpiece blend of Haze, Northern Lights, and Shiva Skunk. It has won numerous awards and is revered as one of the finest sativas ever created.",
    lineage: { parents: ['Haze', 'Northern Lights #5', 'Shiva Skunk'], origin: 'Netherlands', heritage: 'Haze x NL5 x Skunk' },
    breeder: 'Sensi Seeds',
    funFact: "Jack Herer is a prescribed medical strain in the Netherlands under the name 'Bedrocan Sativa.'",
  },
  {
    id: 'white_widow',
    name: 'White Widow',
    type: 'Hybrid',
    era: 'Legacy',
    thcContent: '18% - 25%',
    cbdContent: '0.3%',
    difficulty: 'Easy',
    growthTime: '8-9 weeks',
    expectedYield: 'High (500g/m²)',
    growingTips: [
      'One of the most beginner-friendly strains to grow indoors.',
      'Grows compact and manageable; rarely needs topping.',
      'Covered in white trichomes by week 7 — nearly looks ready before it is.',
    ],
    medicalUses: ['Pain', 'Depression', 'Stress', 'Fatigue', 'PTSD'],
    effects: ['Euphoric', 'Energetic', 'Uplifted', 'Creative', 'Sociable'],
    imageUrl: 'https://images.unsplash.com/photo-1596726581451-b8449c289ad6?auto=format&fit=crop&q=80&w=400',
    description: "A Dutch coffeeshop staple since the mid-1990s that took the cannabis world by storm with its explosive resin production. White Widow's silvery-white buds deliver a powerful burst of euphoria and energy followed by spacious, creative relaxation.",
    lineage: { parents: ['Brazilian Sativa Landrace', 'South Indian Indica'], origin: 'Netherlands', heritage: 'Brazilian x Indian' },
    breeder: 'Green House Seeds',
    funFact: "White Widow won the Cannabis Cup in 1995 and has been a fixture of Amsterdam's coffeeshops for 30+ years.",
  },
  {
    id: 'ak47',
    name: 'AK-47',
    type: 'Hybrid',
    era: 'Legacy',
    thcContent: '17% - 23%',
    cbdContent: '0.1%',
    difficulty: 'Moderate',
    growthTime: '7-9 weeks',
    expectedYield: 'Medium-High (450g/m²)',
    growingTips: [
      'Pungent — carbon filters essential for odor control.',
      'Very sticky — gloves recommended during late-stage trimming.',
      'Resilient and straightforward to grow; handles stress well.',
    ],
    medicalUses: ['Stress', 'Anxiety', 'Depression', 'Pain', 'Insomnia'],
    effects: ['Relaxed', 'Happy', 'Uplifted', 'Mellow', 'Steady'],
    imageUrl: 'https://images.unsplash.com/photo-1629851722960-9ea3c7885b0d?auto=format&fit=crop&q=80&w=400',
    description: "Despite its aggressive name, AK-47 is a mellow, steady strain that leaves you mentally alert while deeply relaxing the body. This multiple Cannabis Cup winner is a precise blend of four world-class landraces, producing long-lasting single-hit satisfaction.",
    lineage: { parents: ['Colombian', 'Mexican', 'Thai', 'Afghani'], origin: 'Netherlands', heritage: 'Quadruple Landrace Cross' },
    breeder: 'Serious Seeds',
    funFact: 'AK-47 has won more cannabis awards than almost any strain in history, including multiple High Times Cannabis Cup victories.',
  },
  {
    id: 'skunk_no1',
    name: 'Skunk #1',
    type: 'Hybrid',
    era: 'Legacy',
    thcContent: '15% - 19%',
    cbdContent: '0.3%',
    difficulty: 'Easy',
    growthTime: '8-9 weeks',
    expectedYield: 'High (500g/m²)',
    growingTips: [
      'The parent of hundreds of modern strains — study this one to understand cannabis genetics.',
      'Extremely vigorous and forgiving; great for beginners.',
      'Produces a very strong, skunky odor — carbon filtration is a must.',
    ],
    medicalUses: ['Stress', 'Anxiety', 'Pain', 'Depression', 'Insomnia'],
    effects: ['Happy', 'Relaxed', 'Uplifted', 'Euphoric', 'Creative'],
    imageUrl: 'https://images.unsplash.com/photo-1542385108-7a544d6db8b1?auto=format&fit=crop&q=80&w=400',
    description: 'The genetic cornerstone of modern cannabis. Developed by Sacred Seeds in California in the late 1970s, Skunk #1 was the first stable hybrid combining multiple landrace genetics. Its influence on subsequent breeding is incalculable.',
    lineage: { parents: ['Afghani', 'Acapulco Gold', 'Colombian Gold'], origin: 'California, USA', heritage: 'Landrace Triple Cross' },
    breeder: 'Sacred Seeds (Sam the Skunkman)',
    funFact: "Skunk #1's genetics flow through nearly 40% of all modern cannabis strains. It's the single most influential strain in breeding history.",
  },
  {
    id: 'northern_lights',
    name: 'Northern Lights',
    type: 'Indica',
    era: 'Legacy',
    thcContent: '16% - 21%',
    difficulty: 'Easy',
    growthTime: '7-9 weeks',
    expectedYield: 'High (550g/m²)',
    growingTips: [
      'Stays short and bushy — excellent for indoor cultivation.',
      'Highly resilient to pests and diseases.',
      'Thrives with standard nutrient regimes.',
    ],
    medicalUses: ['Insomnia', 'Chronic Pain', 'Muscle Spasms', 'Anxiety'],
    effects: ['Sleepy', 'Relaxed', 'Euphoric', 'Hungry'],
    imageUrl: 'https://images.unsplash.com/photo-1542385108-7a544d6db8b1?auto=format&fit=crop&q=80&w=400',
    description: 'One of the most decorated indicas of all time. Northern Lights produces profoundly relaxing effects with dreamy euphoria. A milestone in indoor cannabis cultivation, it paved the way for the modern indoor growing industry.',
    lineage: { parents: ['Afghani Landrace', 'Thai Sativa'], origin: 'Washington, USA', heritage: 'Afghani x Thai' },
    funFact: "Northern Lights won the Cannabis Cup 5 times — more than any other indica strain in the cup's history.",
  },
  {
    id: 'super_silver_haze',
    name: 'Super Silver Haze',
    type: 'Sativa',
    era: 'Legacy',
    thcContent: '18% - 23%',
    cbdContent: '0.1%',
    difficulty: 'Hard',
    growthTime: '10-11 weeks',
    expectedYield: 'High (550g/m²)',
    growingTips: [
      'Stretches dramatically in flower — expect 2-3x height increase.',
      'Needs at least 10 weeks in flower; resist the urge to harvest early.',
      'Responds very well to SCROG training to manage its tall growth.',
    ],
    medicalUses: ['Depression', 'Stress', 'Fatigue', 'Chronic Pain', 'Nausea'],
    effects: ['Energetic', 'Euphoric', 'Creative', 'Uplifted', 'Long-lasting'],
    imageUrl: 'https://images.unsplash.com/photo-1603909223427-51f4f9c6c43e?auto=format&fit=crop&q=80&w=400',
    description: "A 3-time Cannabis Cup champion and the jewel of the Haze family. Super Silver Haze combines the legendary Haze with Northern Lights' resin production and Skunk's growth stability to create one of the most celebrated sativas ever produced.",
    lineage: { parents: ['Skunk #1', 'Northern Lights', 'Haze'], origin: 'Netherlands', heritage: 'Haze x Skunk x NL' },
    breeder: 'Green House Seeds',
    funFact: "Super Silver Haze won the Cannabis Cup three years in a row (1997, 1998, 1999) — an unprecedented achievement.",
  },
  {
    id: 'chemdawg',
    name: 'Chemdawg',
    type: 'Hybrid',
    era: 'Legacy',
    thcContent: '18% - 26%',
    cbdContent: '0.1%',
    difficulty: 'Hard',
    growthTime: '9-10 weeks',
    expectedYield: 'Medium (400g/m²)',
    growingTips: [
      'Very susceptible to mold and mildew — maintain 45-50% humidity in flower.',
      'Extremely pungent; requires serious odor control.',
      'The genetic mother of OG Kush and Sour Diesel — study this lineage carefully.',
    ],
    medicalUses: ['Anxiety', 'Stress', 'PTSD', 'Migraines', 'Chronic Pain'],
    effects: ['Cerebral', 'Euphoric', 'Happy', 'Relaxed', 'Potent'],
    imageUrl: 'https://images.unsplash.com/photo-1629851722960-9ea3c7885b0d?auto=format&fit=crop&q=80&w=400',
    description: 'One of the most mysterious and influential strains in cannabis history. Chemdawg\'s murky origin story involves a Grateful Dead concert parking lot in the late 1980s, but its legacy is undeniable — it is the parent of both OG Kush and Sour Diesel.',
    lineage: { parents: ['Unknown (possibly Thai x Nepalese)'], origin: 'USA (origin disputed)', heritage: 'Unknown Landrace' },
    funFact: 'Chemdawg seeds were discovered in a bag of high-quality cannabis purchased at a Grateful Dead concert in 1991.',
  },

  // ─── MODERN ───────────────────────────────────────────────────────────────

  {
    id: 'blue_dream',
    name: 'Blue Dream',
    type: 'Hybrid',
    era: 'Modern',
    thcContent: '18% - 22%',
    difficulty: 'Easy',
    growthTime: '9-10 weeks',
    expectedYield: 'High (600g/m²)',
    growingTips: [
      'Grows tall; requires topping or pruning early on.',
      'Highly resistant to powdery mildew — great for beginners.',
      'Provide plenty of nitrogen during vegetative stage.',
    ],
    medicalUses: ['Stress Relief', 'Depression', 'Chronic Pain', 'Nausea'],
    effects: ['Uplifting', 'Euphoric', 'Creative', 'Relaxing'],
    imageUrl: 'https://images.unsplash.com/photo-1629851722960-9ea3c7885b0d?auto=format&fit=crop&q=80&w=400',
    description: 'A legendary California sativa-dominant hybrid balancing full-body relaxation with gentle cerebral invigoration. Blue Dream is one of the top-selling strains in legal markets for its versatility and approachable high.',
    lineage: { parents: ['DJ Short Blueberry', 'Super Silver Haze'], origin: 'California, USA', heritage: 'Blueberry x Haze' },
    breeder: 'Santa Cruz',
  },
  {
    id: 'sour_diesel',
    name: 'Sour Diesel',
    type: 'Sativa',
    era: 'Modern',
    thcContent: '20% - 25%',
    difficulty: 'Moderate',
    growthTime: '10-11 weeks',
    expectedYield: 'Medium (450g/m²)',
    growingTips: [
      'Requires low humidity to prevent mold.',
      'Stretches significantly during flowering.',
      'Needs a warm, dry climate between 68-85°F.',
    ],
    medicalUses: ['Fatigue', 'Stress', 'Minor Pain', 'Appetite'],
    effects: ['Energizing', 'Happy', 'Uplifted', 'Talkative'],
    imageUrl: 'https://images.unsplash.com/photo-1596726581451-b8449c289ad6?auto=format&fit=crop&q=80&w=400',
    description: "Named after its pungent diesel-like aroma, this fast-acting New York legend delivers energizing, dreamy cerebral effects that have earned it icon status on both coasts.",
    lineage: { parents: ['Chemdawg 91', 'Super Skunk'], origin: 'New York, USA', heritage: 'Diesel x Skunk' },
  },
  {
    id: 'og_kush',
    name: 'OG Kush',
    type: 'Hybrid',
    era: 'Modern',
    thcContent: '20% - 26%',
    difficulty: 'Hard',
    growthTime: '8-9 weeks',
    expectedYield: 'Medium (400g/m²)',
    growingTips: [
      'Susceptible to powdery mildew — maintain airflow.',
      'Requires heavy feeding with calcium & magnesium.',
      'Frequent pruning encourages proper canopy development.',
    ],
    medicalUses: ['Migraines', 'ADD/ADHD', 'Stress', 'Severe Pain'],
    effects: ['Euphoric', 'Happy', 'Relaxed', 'Giggly'],
    imageUrl: 'https://images.unsplash.com/photo-1629851722960-9ea3c7885b0d?auto=format&fit=crop&q=80&w=400',
    description: "The genetic backbone of West Coast cannabis. OG Kush's complex terpene profile of fuel, skunk, and spice delivers heavy mixed head and body effects that defined California cannabis culture.",
    lineage: { parents: ['Chemdawg', 'Hindu Kush'], origin: 'Florida, USA', heritage: 'Kush x Chemdawg' },
  },
  {
    id: 'girl_scout_cookies',
    name: 'Girl Scout Cookies (GSC)',
    type: 'Hybrid',
    era: 'Modern',
    thcContent: '25% - 28%',
    difficulty: 'Moderate',
    growthTime: '9-10 weeks',
    expectedYield: 'Medium (450g/m²)',
    growingTips: [
      'Very resistant to pests and diseases.',
      'Keep humidity below 50% to avoid mold on dense buds.',
      'Benefits greatly from low-stress training (LST).',
    ],
    medicalUses: ['Severe Pain', 'Nausea', 'Appetite Loss', 'Depression'],
    effects: ['Happy', 'Relaxed', 'Euphoric', 'Creative'],
    imageUrl: 'https://images.unsplash.com/photo-1596726581451-b8449c289ad6?auto=format&fit=crop&q=80&w=400',
    description: 'Award-winning Bay Area hybrid with a pungent dessert aroma of mint, sweet cherry, and lemon. GSC delivers euphoric cerebral effects alongside heavy full-body relaxation.',
    lineage: { parents: ['OG Kush', 'Durban Poison'], origin: 'San Francisco, CA', heritage: 'Cookies x Kush' },
  },
  {
    id: 'gorilla_glue_4',
    name: 'Gorilla Glue #4',
    type: 'Hybrid',
    era: 'Modern',
    thcContent: '25% - 30%',
    cbdContent: '0.1%',
    difficulty: 'Moderate',
    growthTime: '8-9 weeks',
    expectedYield: 'High (600g/m²)',
    growingTips: [
      'Produces enormous amounts of resin — scissors and hands glue up instantly during trimming.',
      'Scrog training dramatically increases yield potential.',
      'Watch for moisture in dense buds during late flower.',
    ],
    medicalUses: ['Depression', 'Insomnia', 'Pain', 'PTSD', 'Muscle Spasms'],
    effects: ['Euphoric', 'Relaxed', 'Heavy', 'Happy', 'Sedated'],
    imageUrl: 'https://images.unsplash.com/photo-1542385108-7a544d6db8b1?auto=format&fit=crop&q=80&w=400',
    description: "GG#4's absurd resin production — so sticky it makes scissors unusable — and its heavyweight couch-lock effects made it a sensation when it first emerged. A multiple Cannabis Cup winner and one of the decade's most influential strains.",
    lineage: { parents: ['Chem Sister', 'Sour Dubb', 'Chocolate Diesel'], origin: 'USA', heritage: 'Chem x Sour x Diesel' },
    breeder: 'GG Strains',
    funFact: "GG#4 was created by accident — Joesy Whales's entire Chem Sis crop became hermaphroditic, but one accidental cross produced GG#4.",
  },
  {
    id: 'wedding_cake',
    name: 'Wedding Cake',
    type: 'Hybrid',
    era: 'Modern',
    thcContent: '24% - 27%',
    cbdContent: '0.1%',
    difficulty: 'Moderate',
    growthTime: '8-9 weeks',
    expectedYield: 'High (550g/m²)',
    growingTips: [
      'Dense buds benefit from defoliation to improve airflow and light penetration.',
      'Rich in caryophyllene — a pepper-rich terpene known for anti-inflammatory properties.',
      'Tolerates both indoor and outdoor cultivation well.',
    ],
    medicalUses: ['Anxiety', 'Pain', 'Insomnia', 'Stress', 'Appetite Loss'],
    effects: ['Relaxed', 'Happy', 'Euphoric', 'Uplifted', 'Hungry'],
    imageUrl: 'https://images.unsplash.com/photo-1629851722960-9ea3c7885b0d?auto=format&fit=crop&q=80&w=400',
    description: "Also known as Pink Cookies, Wedding Cake is a rich tangy indica-dominant strain with undertones of earthy pepper. Its dense, resin-covered buds and bakery-like aroma have made it one of the most popular strains sold in legal dispensaries.",
    lineage: { parents: ['Triangle Kush', 'Animal Mints'], origin: 'California, USA', heritage: 'Cookies x Kush' },
    breeder: 'Seed Junky Genetics',
  },
  {
    id: 'gelato',
    name: 'Gelato',
    type: 'Hybrid',
    era: 'Modern',
    thcContent: '20% - 26%',
    cbdContent: '0.1%',
    difficulty: 'Moderate',
    growthTime: '8-9 weeks',
    expectedYield: 'Medium (450g/m²)',
    growingTips: [
      'Produces colorful purple and orange phenotypes — cooler night temperatures enhance coloring.',
      'Multiple phenotypes exist (Gelato #33 "Larry Bird" is most celebrated).',
      'Dense buds need low humidity to prevent mold; keep below 45% in late flower.',
    ],
    medicalUses: ['Muscle Spasms', 'Chronic Pain', 'Fatigue', 'Inflammation'],
    effects: ['Euphoric', 'Relaxed', 'Creative', 'Energetic', 'Uplifted'],
    imageUrl: 'https://images.unsplash.com/photo-1596726581451-b8449c289ad6?auto=format&fit=crop&q=80&w=400',
    description: "Sunset Sherbet and Thin Mint GSC combined to create this dessert-flavored California masterpiece. Gelato delivers a potent rush of euphoria and relaxation without heavy sedation, wrapped in a sweet, fruity, sherbet-like aroma.",
    lineage: { parents: ['Sunset Sherbet', 'Thin Mint Girl Scout Cookies'], origin: 'San Francisco, CA', heritage: 'Cookies x Sherbet' },
    breeder: 'Cookie Fam Genetics',
  },
  {
    id: 'zkittlez',
    name: 'Zkittlez',
    type: 'Indica',
    era: 'Modern',
    thcContent: '15% - 23%',
    cbdContent: '0.2%',
    difficulty: 'Moderate',
    growthTime: '8-9 weeks',
    expectedYield: 'Medium (400g/m²)',
    growingTips: [
      'Stays compact and manageable — excellent for small indoor spaces.',
      'Produces vibrant aromas of grape, grapefruit, and tropical fruit.',
      'Benefits from calcium and magnesium supplements throughout the grow.',
    ],
    medicalUses: ['Stress', 'Anxiety', 'Pain', 'Depression', 'Insomnia'],
    effects: ['Happy', 'Relaxed', 'Uplifted', 'Calm', 'Sleepy'],
    imageUrl: 'https://images.unsplash.com/photo-1542385108-7a544d6db8b1?auto=format&fit=crop&q=80&w=400',
    description: "Named for the candy, Zkittlez dazzles with an explosion of tropical, fruity aromas and a calm, winning euphoria that fades into deep full-body relaxation. A multiple Cannabis Cup champion and one of the most colorful, flavorful strains available.",
    lineage: { parents: ['Grape Ape', 'Grapefruit', 'Unknown Third Parent'], origin: 'California, USA', heritage: 'Fruit Cross' },
    breeder: 'Dying Breed Seeds / 3rd Gen Family',
  },

  // ─── ADDITIONAL LANDRACES ─────────────────────────────────────────────────
  {
    id: 'malawi_gold',
    name: 'Malawi Gold',
    type: 'Sativa',
    era: 'Landrace',
    thcContent: '16% - 22%',
    difficulty: 'Hard',
    growthTime: '14-16 weeks',
    expectedYield: 'Low (250g/m²)',
    growingTips: ['Requires tropical outdoor climate — nearly impossible indoors without serious setup.', 'One of the tallest cannabis plants in existence; can reach 5+ meters outdoors.'],
    medicalUses: ['Depression', 'Fatigue', 'Creative Blocks'],
    effects: ['Psychedelic', 'Euphoric', 'Energetic', 'Visionary', 'Clear-headed'],
    imageUrl: 'https://images.unsplash.com/photo-1603909223427-51f4f9c6c43e?auto=format&fit=crop&q=80&w=400',
    description: '100% pure African sativa from the shores of Lake Malawi. Legendary for its towering height, long colas, and uniquely clear psychedelic cerebral high — used in traditional ceremonies for centuries.',
    lineage: { parents: ['Pure African Sativa'], origin: 'Malawi, Africa', heritage: 'Pure African Sativa' },
    funFact: 'Malawi Gold cobs — compressed cannabis wrapped in banana leaves — were among the most prized exports from sub-Saharan Africa in the 1970s.',
  },
  {
    id: 'punto_rojo',
    name: 'Punto Rojo',
    type: 'Sativa',
    era: 'Landrace',
    thcContent: '14% - 18%',
    difficulty: 'Hard',
    growthTime: '12-14 weeks',
    expectedYield: 'Low (250g/m²)',
    growingTips: ['Best grown outdoors in equatorial climates.', 'Named for the distinctive reddish dots on its pistils — monitor for full maturity.'],
    medicalUses: ['Depression', 'Fatigue', 'Stress'],
    effects: ['Uplifted', 'Creative', 'Euphoric', 'Energetic'],
    imageUrl: 'https://images.unsplash.com/photo-1603909223427-51f4f9c6c43e?auto=format&fit=crop&q=80&w=400',
    description: "A rare Colombian landrace prized by indigenous communities for generations. Punto Rojo ('red dot') is named for its distinctive reddish pistils and delivers a soaring, long-lasting cerebral high.",
    lineage: { parents: ['Colombian Landrace'], origin: 'Colombia', heritage: 'Pure Colombian Sativa' },
    funFact: 'Considered sacred by the Kogi people of Colombia, who have cultivated and preserved this genetics for over 1,000 years.',
  },
  {
    id: 'nepalese',
    name: 'Nepalese',
    type: 'Hybrid',
    era: 'Landrace',
    thcContent: '12% - 18%',
    difficulty: 'Moderate',
    growthTime: '10-12 weeks',
    expectedYield: 'Medium (300g/m²)',
    growingTips: ['High-altitude adaptation means it handles temperature swings well — useful for outdoor grows in variable climates.', 'Traditionally harvested for hand-rubbed charas (live resin hash).'],
    medicalUses: ['Pain', 'Anxiety', 'Stress', 'Fatigue'],
    effects: ['Relaxed', 'Happy', 'Euphoric', 'Peaceful', 'Balanced'],
    imageUrl: 'https://images.unsplash.com/photo-1542385108-7a544d6db8b1?auto=format&fit=crop&q=80&w=400',
    description: 'A high-altitude landrace from the Himalayan foothills of Nepal, grown for centuries for both smoking and charas (hand-rolled hash) production. Balanced effects from uniquely rugged high-altitude genetics.',
    lineage: { parents: ['Nepalese Landrace'], origin: 'Nepal / Himalayas', heritage: 'Pure Himalayan Landrace' },
    funFact: 'Nepalese charas — hand-rubbed live hash — was the primary cannabis product traded along the 1970s Hippie Trail from Kathmandu to Amsterdam.',
  },
  {
    id: 'lebanese_blonde',
    name: 'Lebanese Blonde',
    type: 'Sativa',
    era: 'Landrace',
    thcContent: '12% - 17%',
    difficulty: 'Moderate',
    growthTime: '10-11 weeks',
    expectedYield: 'Medium (300g/m²)',
    growingTips: ['Adapts well to Mediterranean climates.', 'Traditionally grown for blonde hash production — let plants cure naturally for best aroma.'],
    medicalUses: ['Anxiety', 'Stress', 'Depression'],
    effects: ['Clear-headed', 'Functional', 'Mellow', 'Happy', 'Sociable'],
    imageUrl: 'https://images.unsplash.com/photo-1603909223427-51f4f9c6c43e?auto=format&fit=crop&q=80&w=400',
    description: "One of the world's oldest cultivated cannabis varieties, grown in Lebanon's Bekaa Valley for over 2,000 years. Famous for producing premium blonde Lebanese hash — a staple of 1970s European counterculture.",
    lineage: { parents: ['Lebanese Landrace'], origin: 'Bekaa Valley, Lebanon', heritage: 'Pure Lebanese Sativa' },
    funFact: "Lebanese Red and Blonde hash commanded premium prices in 1970s Europe and was a key commodity along the 'Hippie Trail.'",
  },

  // ─── ADDITIONAL LEGACY ────────────────────────────────────────────────────
  {
    id: 'blueberry_dj_short',
    name: "Blueberry (DJ Short)",
    type: 'Indica',
    era: 'Legacy',
    thcContent: '15% - 20%',
    difficulty: 'Hard',
    growthTime: '8-10 weeks',
    expectedYield: 'Medium (400g/m²)',
    growingTips: ['Produces multiple phenotypes — the best express a vivid blueberry aroma.', 'Cooler night temps in late flower bring out stunning purple and blue coloring.'],
    medicalUses: ['Insomnia', 'Pain', 'Stress', 'PTSD'],
    effects: ['Relaxed', 'Dreamy', 'Happy', 'Euphoric', 'Sleepy'],
    imageUrl: 'https://images.unsplash.com/photo-1542385108-7a544d6db8b1?auto=format&fit=crop&q=80&w=400',
    description: "DJ Short's masterwork — a perfectly balanced indica created by crossing Highland Thai and Purple Thai with Afghani. Produces intensely blueberry-scented buds with a long-lasting, dreamy body high.",
    lineage: { parents: ['Highland Thai', 'Purple Thai', 'Afghani'], origin: 'USA', heritage: 'Thai x Afghani' },
    breeder: 'DJ Short',
    funFact: 'Blueberry won the 2000 High Times Cannabis Cup for Best Indica. Its blueberry terpene profile has been chased by breeders for over 40 years.',
  },
  {
    id: 'purple_haze',
    name: 'Purple Haze',
    type: 'Sativa',
    era: 'Legacy',
    thcContent: '17% - 20%',
    difficulty: 'Moderate',
    growthTime: '9-10 weeks',
    expectedYield: 'Medium (400g/m²)',
    growingTips: ['Provides classic haze stretch — expect significant height increase in flower.', 'Cool temps in late flower enhance the purple coloration from its Thai parent.'],
    medicalUses: ['Depression', 'Fatigue', 'Stress', 'Pain'],
    effects: ['Euphoric', 'Creative', 'Energetic', 'Psychedelic', 'Dreamy'],
    imageUrl: 'https://images.unsplash.com/photo-1603909223427-51f4f9c6c43e?auto=format&fit=crop&q=80&w=400',
    description: "Immortalized by Jimi Hendrix's 1967 anthem, Purple Haze is a classic 60s-era sativa with an earthy spice and sweet berry aroma, delivering a psychedelic, expansive cerebral experience.",
    lineage: { parents: ['Haze', 'Purple Thai'], origin: 'USA', heritage: 'Haze x Thai' },
    funFact: "Jimi Hendrix's 'Purple Haze' was written in 1966 and is widely believed to reference this legendary strain, though Hendrix himself never confirmed it.",
  },
  {
    id: 'trainwreck',
    name: 'Trainwreck',
    type: 'Hybrid',
    era: 'Legacy',
    thcContent: '18% - 25%',
    difficulty: 'Moderate',
    growthTime: '8-10 weeks',
    expectedYield: 'High (500g/m²)',
    growingTips: ['Sativa-dominant stretch — top early to manage height.', 'Generates a powerful lemon-pine aroma; strong odor control needed.'],
    medicalUses: ['Pain', 'PTSD', 'Anxiety', 'Migraines', 'ADHD'],
    effects: ['Euphoric', 'Energetic', 'Creative', 'Happy', 'Relaxed'],
    imageUrl: 'https://images.unsplash.com/photo-1629851722960-9ea3c7885b0d?auto=format&fit=crop&q=80&w=400',
    description: "A California legend with a name that describes its effect — a fast-hitting rush of euphoria and mental stimulation from its sativa parents, mellowing into full-body relaxation from its Afghani roots.",
    lineage: { parents: ['Mexican Sativa', 'Thai Sativa', 'Afghani Indica'], origin: 'Humboldt County, CA', heritage: 'Mexican x Thai x Afghani' },
    funFact: 'Trainwreck originated in Humboldt County in the 1970s and allegedly got its name from a train derailment near the original grow site.',
  },
  {
    id: 'g13',
    name: 'G13',
    type: 'Indica',
    era: 'Legacy',
    thcContent: '22% - 28%',
    difficulty: 'Hard',
    growthTime: '8-9 weeks',
    expectedYield: 'Medium (400g/m²)',
    growingTips: ['Extremely resinous — keep humidity low in flower.', 'Legend strain; grow it with respect and attention to detail.'],
    medicalUses: ['Pain', 'Insomnia', 'Muscle Spasms', 'PTSD'],
    effects: ['Sedated', 'Euphoric', 'Relaxed', 'Heavy', 'Couch-lock'],
    imageUrl: 'https://images.unsplash.com/photo-1542385108-7a544d6db8b1?auto=format&fit=crop&q=80&w=400',
    description: "One of cannabis's greatest legends. G13 is said to have been developed by the US government at the University of Mississippi, with a single clone stolen in the 1970s. Real or myth — its potency is undeniable.",
    lineage: { parents: ['Unknown (Government experiment — alleged)'], origin: 'Mississippi, USA (alleged)', heritage: 'Unknown Pure Indica' },
    funFact: 'G13 appeared in the 1999 film American Beauty and the novel Trainspotting, cementing its legendary status in popular culture.',
  },
  {
    id: 'bubba_kush',
    name: 'Bubba Kush',
    type: 'Indica',
    era: 'Legacy',
    thcContent: '17% - 22%',
    difficulty: 'Easy',
    growthTime: '8-9 weeks',
    expectedYield: 'Medium (400g/m²)',
    growingTips: ['Compact and easy to manage indoors.', 'Chocolate-coffee aroma intensifies in the final 2 weeks of flower — do not harvest early.'],
    medicalUses: ['Insomnia', 'Anxiety', 'Muscle Spasms', 'Stress', 'PTSD'],
    effects: ['Sedated', 'Relaxed', 'Sleepy', 'Happy', 'Euphoric'],
    imageUrl: 'https://images.unsplash.com/photo-1542385108-7a544d6db8b1?auto=format&fit=crop&q=80&w=400',
    description: "An American classic with mysterious New Orleans origins and OG Kush genetics. Bubba Kush delivers a heavy tranquilizing effect with a distinctive chocolate-coffee aroma, making it one of the premier sleep indicas.",
    lineage: { parents: ['OG Kush', 'Unknown Indica'], origin: 'California, USA', heritage: 'Kush x Unknown' },
    funFact: 'Bubba Kush emerged around 1996 when an OG Kush plant was accidentally cross-pollinated by an unknown indica from New Orleans.',
  },
  {
    id: 'granddaddy_purple',
    name: 'Granddaddy Purple (GDP)',
    type: 'Indica',
    era: 'Legacy',
    thcContent: '17% - 23%',
    difficulty: 'Easy',
    growthTime: '8-11 weeks',
    expectedYield: 'High (550g/m²)',
    growingTips: ['Cool night temperatures (10-15°F drop) unlock vivid purple coloring.', 'Dense buds benefit from defoliation and airflow to prevent botrytis.'],
    medicalUses: ['Pain', 'Insomnia', 'Stress', 'Appetite Loss', 'Muscle Spasms'],
    effects: ['Relaxed', 'Sleepy', 'Happy', 'Euphoric', 'Dreamy'],
    imageUrl: 'https://images.unsplash.com/photo-1542385108-7a544d6db8b1?auto=format&fit=crop&q=80&w=400',
    description: 'Introduced by Ken Estes in California in 2003, GDP quickly became the definitive purple indica. Its striking violet buds and complex berry-grape aroma set the standard for the entire purple cannabis category.',
    lineage: { parents: ['Purple Urkle', 'Big Bud'], origin: 'California, USA', heritage: 'Urkle x Big Bud' },
    funFact: "GDP's purple pigmentation comes from anthocyanins activated by cool temperatures — the same compounds that turn autumn leaves red and orange.",
  },
  {
    id: 'nyc_diesel',
    name: 'NYC Diesel',
    type: 'Hybrid',
    era: 'Legacy',
    thcContent: '19% - 22%',
    difficulty: 'Moderate',
    growthTime: '9-10 weeks',
    expectedYield: 'Medium (500g/m²)',
    growingTips: ['Produces heavy citrus aroma — carbon filter essential.', 'Multiple Cannabis Cup medalist; runs well in both soil and hydro.'],
    medicalUses: ['Stress', 'Depression', 'Fatigue', 'Pain'],
    effects: ['Happy', 'Uplifted', 'Energetic', 'Creative', 'Sociable'],
    imageUrl: 'https://images.unsplash.com/photo-1603909223427-51f4f9c6c43e?auto=format&fit=crop&q=80&w=400',
    description: 'A New York icon by Soma Seeds — NYC Diesel blends classic diesel fuel notes with grapefruit citrus for one of the most distinctive aromatic profiles in cannabis. Five Cannabis Cup medals tell its story.',
    lineage: { parents: ['Sour Diesel', 'Afghani / Hawaiian'], origin: 'New York, USA', heritage: 'Diesel x Afghani x Hawaiian' },
    breeder: 'Soma Seeds',
    funFact: 'NYC Diesel won 5 Cannabis Cup medals, making it one of the most decorated strains of the early 2000s.',
  },

  // ─── ADDITIONAL MODERN ────────────────────────────────────────────────────
  {
    id: 'mac',
    name: 'MAC (Miracle Alien Cookies)',
    type: 'Hybrid',
    era: 'Modern',
    thcContent: '20% - 23%',
    difficulty: 'Hard',
    growthTime: '9-10 weeks',
    expectedYield: 'Medium (450g/m²)',
    growingTips: ['Extremely resinous — experienced growers only.', 'Initially distributed for free online by creator Capulator; now one of the most cloned strains globally.'],
    medicalUses: ['Anxiety', 'Depression', 'Stress', 'Pain'],
    effects: ['Euphoric', 'Relaxed', 'Uplifted', 'Creative', 'Happy'],
    imageUrl: 'https://images.unsplash.com/photo-1629851722960-9ea3c7885b0d?auto=format&fit=crop&q=80&w=400',
    description: 'One of the most sought-after modern strains. MAC produces glistening trichome-drenched buds with a complex creamy gas aroma and a perfectly balanced euphoric high that made it an instant legend.',
    lineage: { parents: ['Alien Cookies', 'Colombian x Starfighter'], origin: 'USA', heritage: 'Alien x Colombian x Starfighter' },
    breeder: 'Capulator',
    funFact: 'MAC was initially given away for free by its creator on cannabis forums and became one of the most counterfeited strains in history.',
  },
  {
    id: 'runtz',
    name: 'Runtz',
    type: 'Hybrid',
    era: 'Modern',
    thcContent: '19% - 29%',
    difficulty: 'Hard',
    growthTime: '8-9 weeks',
    expectedYield: 'Medium (400g/m²)',
    growingTips: ['Dense, colorful buds — keep humidity below 45% in late flower.', 'Its candy-like terpene profile is best expressed in living soil.'],
    medicalUses: ['Stress', 'Anxiety', 'Pain', 'Insomnia'],
    effects: ['Euphoric', 'Happy', 'Uplifted', 'Relaxed', 'Tingly'],
    imageUrl: 'https://images.unsplash.com/photo-1629851722960-9ea3c7885b0d?auto=format&fit=crop&q=80&w=400',
    description: "The strain of the 2020s. Runtz's creamy tropical candy aroma and balanced euphoric body high made it an instant cultural phenomenon — one of the most photographed and counterfeited strains in cannabis history.",
    lineage: { parents: ['Zkittlez', 'Gelato'], origin: 'California, USA', heritage: 'Zkittlez x Gelato' },
    funFact: 'Counterfeit Runtz packaging flooded unregulated markets after its rise, sparking major industry conversations about cannabis brand protection.',
  },
  {
    id: 'mimosa',
    name: 'Mimosa',
    type: 'Sativa',
    era: 'Modern',
    thcContent: '17% - 27%',
    difficulty: 'Moderate',
    growthTime: '8-9 weeks',
    expectedYield: 'High (500g/m²)',
    growingTips: ['Morning-friendly — citrus terpenes peak at harvest when temps are managed carefully.', 'One of the highest-testing sativas on the legal market.'],
    medicalUses: ['Depression', 'Fatigue', 'Stress', 'Anxiety'],
    effects: ['Energetic', 'Uplifted', 'Happy', 'Focused', 'Sociable'],
    imageUrl: 'https://images.unsplash.com/photo-1603909223427-51f4f9c6c43e?auto=format&fit=crop&q=80&w=400',
    description: 'Named for the brunch cocktail it mimics — citrusy, bubbly, mood-boosting. Mimosa is a morning-friendly sativa-dominant strain delivering clear functional energy with a bright orange-grapefruit aroma.',
    lineage: { parents: ['Purple Punch', 'Clementine'], origin: 'California, USA', heritage: 'Punch x Clementine' },
    funFact: 'Mimosa averages above 26% THC in many tested cuts, making it one of the strongest daily-use sativas currently on the legal market.',
  },
  {
    id: 'ice_cream_cake',
    name: 'Ice Cream Cake',
    type: 'Indica',
    era: 'Modern',
    thcContent: '20% - 25%',
    difficulty: 'Moderate',
    growthTime: '8-9 weeks',
    expectedYield: 'Medium (400g/m²)',
    growingTips: ['Terpene profile dominated by limonene, caryophyllene, and linalool — an unusually sweet combination.', 'Defoliate for airflow around dense colas in mid-flower.'],
    medicalUses: ['Insomnia', 'Anxiety', 'Pain', 'Stress'],
    effects: ['Relaxed', 'Euphoric', 'Sleepy', 'Happy', 'Hungry'],
    imageUrl: 'https://images.unsplash.com/photo-1542385108-7a544d6db8b1?auto=format&fit=crop&q=80&w=400',
    description: "A Seed Junky Genetics masterpiece smelling of rich vanilla cake batter with creamy cheese undertones. Its effects are equally indulgent: heavy, euphoric, and deeply sedating with a slow full-body melt.",
    lineage: { parents: ['Wedding Cake', 'Gelato #33'], origin: 'California, USA', heritage: 'Wedding Cake x Gelato' },
    breeder: 'Seed Junky Genetics',
    funFact: 'Ice Cream Cake has one of the most complex terpene profiles of any modern indica, making it a benchmark strain for extraction artists.',
  },
  {
    id: 'strawberry_cough',
    name: 'Strawberry Cough',
    type: 'Sativa',
    era: 'Modern',
    thcContent: '15% - 20%',
    difficulty: 'Moderate',
    growthTime: '9 weeks',
    expectedYield: 'Medium (400g/m²)',
    growingTips: ['Sweet strawberry aroma peaks in the final week of flower.', 'Recommended for anxiety relief due to its clean, non-paranoia-inducing high.'],
    medicalUses: ['Anxiety', 'Stress', 'Depression', 'PTSD'],
    effects: ['Euphoric', 'Uplifted', 'Happy', 'Creative', 'Sociable'],
    imageUrl: 'https://images.unsplash.com/photo-1603909223427-51f4f9c6c43e?auto=format&fit=crop&q=80&w=400',
    description: "A beloved sativa with unmistakable sweet strawberry aroma. Strawberry Cough's clean, expansive high and manageable potency have made it a staple recommendation for anxiety and social situations.",
    lineage: { parents: ['Strawberry Fields', 'Haze'], origin: 'Vermont, USA', heritage: 'Strawberry x Haze' },
    funFact: "Strawberry Cough was featured in 'Children of Men' (2006) as the last great luxury of a dying civilization — a testament to its iconic status.",
  },
  {
    id: 'dosidos',
    name: 'Do-Si-Dos',
    type: 'Indica',
    era: 'Modern',
    thcContent: '19% - 30%',
    difficulty: 'Moderate',
    growthTime: '8-9 weeks',
    expectedYield: 'Medium (400g/m²)',
    growingTips: ['Exceptional resin production — one of the best parent strains for breeding.', 'Has become a cornerstone of the exotic breeding world; hundreds of Do-Si-Dos crosses exist.'],
    medicalUses: ['Insomnia', 'Pain', 'Stress', 'Anxiety', 'Nausea'],
    effects: ['Relaxed', 'Euphoric', 'Happy', 'Sleepy', 'Body-heavy'],
    imageUrl: 'https://images.unsplash.com/photo-1542385108-7a544d6db8b1?auto=format&fit=crop&q=80&w=400',
    description: "A heavy, complex indica with pungent OG and sweet floral notes. Do-Si-Dos' extreme resin production — catching glints of every color under a light — has made it a legend in both consumption and modern breeding.",
    lineage: { parents: ['Girl Scout Cookies', 'Face Off OG'], origin: 'California, USA', heritage: 'GSC x Face Off OG' },
    funFact: 'Do-Si-Dos has become one of the most used parent strains in modern exotic breeding — its genetics appear in hundreds of new cultivars.',
  },
  {
    id: 'purple_punch',
    name: 'Purple Punch',
    type: 'Indica',
    era: 'Modern',
    thcContent: '18% - 20%',
    difficulty: 'Easy',
    growthTime: '7-8 weeks',
    expectedYield: 'High (500g/m²)',
    growingTips: ['Consistently produces vivid purple buds even without temperature manipulation.', 'Fast-finishing and beginner-friendly despite its premium genetics.'],
    medicalUses: ['Insomnia', 'Stress', 'Pain', 'Nausea', 'Headaches'],
    effects: ['Sleepy', 'Relaxed', 'Happy', 'Euphoric', 'Hungry'],
    imageUrl: 'https://images.unsplash.com/photo-1542385108-7a544d6db8b1?auto=format&fit=crop&q=80&w=400',
    description: "A one-two punch of Larry OG and Granddaddy Purple. Purple Punch hits hard with a grape candy and blueberry muffin aroma and delivers fast-acting couch-lock euphoria — one of the best sleep indicas available.",
    lineage: { parents: ['Larry OG', 'Granddaddy Purple'], origin: 'California, USA', heritage: 'Kush x GDP' },
    funFact: 'Purple Punch produces striking purple buds consistently across phenotypes — one of the few modern strains that does so without temperature tricks.',
  },
  {
    id: 'gmo_cookies',
    name: 'GMO Cookies (Garlic Cookies)',
    type: 'Hybrid',
    era: 'Modern',
    thcContent: '20% - 30%',
    difficulty: 'Hard',
    growthTime: '9-10 weeks',
    expectedYield: 'Medium (450g/m²)',
    growingTips: ['Garlic-diesel aroma is extremely pungent — carbon filtration essential.', 'Top-shelf potency; grown by experienced cultivators for the connoisseur market.'],
    medicalUses: ['Pain', 'Insomnia', 'Anxiety', 'PTSD', 'Muscle Spasms'],
    effects: ['Sedated', 'Relaxed', 'Euphoric', 'Happy', 'Body-heavy'],
    imageUrl: 'https://images.unsplash.com/photo-1629851722960-9ea3c7885b0d?auto=format&fit=crop&q=80&w=400',
    description: "GMO (Garlic, Mushroom, Onion) Cookies polarizes opinion with its intensely savory diesel-garlic aroma while delivering knock-out potency revered by connoisseurs and extractors alike.",
    lineage: { parents: ['Girl Scout Cookies', 'Chemdawg'], origin: 'California, USA', heritage: 'GSC x Chemdawg' },
    breeder: 'Divine Genetics',
    funFact: "GMO Cookies — also called Garlic Cookies — has become the cornerstone of the high-potency 'exotic' market, setting new standards for THC percentage.",
  },
  {
    id: 'apple_fritter',
    name: 'Apple Fritter',
    type: 'Hybrid',
    era: 'Modern',
    thcContent: '22% - 28%',
    difficulty: 'Hard',
    growthTime: '8-9 weeks',
    expectedYield: 'Medium (400g/m²)',
    growingTips: ['One of the rarest strains in licensed California dispensaries.', 'Complex sour apple and vanilla pastry terpene profile — best preserved in cold living soil environments.'],
    medicalUses: ['Stress', 'Pain', 'Depression', 'Insomnia'],
    effects: ['Relaxed', 'Happy', 'Euphoric', 'Uplifted', 'Sedated'],
    imageUrl: 'https://images.unsplash.com/photo-1629851722960-9ea3c7885b0d?auto=format&fit=crop&q=80&w=400',
    description: 'One of the rarest and highest-rated strains in the legal California market. Apple Fritter has achieved near-mythical status for its perfect mix of sour apple and vanilla pastry aroma and long-lasting balanced high.',
    lineage: { parents: ['Sour Apple', 'Animal Cookies'], origin: 'California, USA', heritage: 'Sour Apple x Animal Cookies' },
    funFact: 'Apple Fritter has tested above 30% THC in multiple lab results, making it one of the strongest strains ever recorded on the legal market.',
  },

];

export async function fetchStrains(query?: string, type?: StrainType, difficulty?: Difficulty, era?: StrainEra): Promise<StrainInfo[]> {
  await new Promise(resolve => setTimeout(resolve, 300));
  let results = [...strainDatabase];

  if (query) {
    const q = query.toLowerCase();
    results = results.filter(s =>
      s.name.toLowerCase().includes(q) ||
      s.description.toLowerCase().includes(q) ||
      s.lineage.origin?.toLowerCase().includes(q) ||
      s.lineage.parents.some(p => p.toLowerCase().includes(q)) ||
      (s.lineage.heritage && s.lineage.heritage.toLowerCase().includes(q)) ||
      (s.funFact && s.funFact.toLowerCase().includes(q))
    );
  }

  if (type) results = results.filter(s => s.type === type);
  if (difficulty) results = results.filter(s => s.difficulty === difficulty);
  if (era) results = results.filter(s => s.era === era);

  return results;
}

export async function getStrainById(id: string): Promise<StrainInfo | null> {
  return strainDatabase.find(s => s.id === id) || null;
}

export async function getStrainEras(): Promise<StrainEra[]> {
  return ['Landrace', 'Legacy', 'Modern'];
}